import { EdgeGatewaySslVpnAuthServerJson } from './__json__/edge-gateway-ssl-vpn-auth-server-json';
import { EdgeGatewaySslVpnAuthServerType } from './edge-gateway-ssl-vpn-auth-server-type';

/* istanbul ignore next: autogenerated */
export class EdgeGatewaySslVpnAuthServer {

  constructor(private _authServerJson: EdgeGatewaySslVpnAuthServerJson) {
  }

  /**
   * Get auth server type.
   * @returns {EdgeGatewaySslVpnAuthServerType}
   */
  get authServerType(): EdgeGatewaySslVpnAuthServerType {
    return this._authServerJson.auth_server_type;
  }

  /**
   * Get the json representation of this class.
   * @returns {EdgeGatewaySslVpnAuthServerJson}
   */
  get json(): EdgeGatewaySslVpnAuthServerJson {
    return Object.assign({}, this._authServerJson);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._authServerJson, undefined, 2);
  }
}
