import { EdgeGatewaySslVpnRsaAuthServerJson } from './__json__/edge-gateway-ssl-vpn-rsa-auth-server-json';
import { EdgeGatewaySslVpnAuthServer } from './edge-gateway-ssl-vpn-auth-server';
import { EdgeGatewaySslVpnAuthServerType } from './edge-gateway-ssl-vpn-auth-server-type';

/* istanbul ignore next: autogenerated */
export class EdgeGatewaySslVpnRsaAuthServer extends EdgeGatewaySslVpnAuthServer {

  constructor(private _json: EdgeGatewaySslVpnRsaAuthServerJson) {
    super(_json);
  }

  /**
   * Get enabled.
   * @returns {boolean}
   */
  get enabled(): boolean {
    return this._json.enabled;
  }

  /**
   * Get secondary auth server.
   * @returns {boolean}
   */
  get secondaryAuthServer(): boolean {
    return this._json.secondary_auth_server;
  }

  /**
   * Get terminate session on auth fails.
   * @returns {boolean}
   */
  get terminateSessionOnAuthFails(): boolean {
    return this._json.terminate_session_on_auth_fails;
  }

  /**
   * Get timeout.
   * @returns {number}
   */
  get timeout(): number {
    return this._json.timeout;
  }

  /**
   * Get config file.
   * @returns {string}
   */
  get configFile(): string {
    return this._json.config_file;
  }

  /**
   * Get source ip.
   * @returns {string}
   */
  get sourceIp(): string {
    return this._json.source_ip;
  }

  /**
   * Get auth server type.
   * @returns {EdgeGatewaySslVpnAuthServerType}
   */
  get authServerType(): EdgeGatewaySslVpnAuthServerType {
    return this._json.auth_server_type;
  }

  /**
   * Get the json representation of this class.
   * @returns {EdgeGatewaySslVpnRsaAuthServerJson}
   */
  get json(): EdgeGatewaySslVpnRsaAuthServerJson {
    return Object.assign({}, this._json);
  }

  /**
   * Get the string representation of this class.
   * @returns {string}
   */
  toString(): string {
    return JSON.stringify(this._json, undefined, 2);
  }
}
